name: Assignment 6 Model Tests

on:
  push:
    branches: [ main, Assignment6 ]
    paths:
      - '**'
  pull_request:
    branches: [ main ]
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p models
        mkdir -p outputs
        chmod -R 777 outputs  # Ensure write permissions
        echo "Created models and outputs directories"

    - name: Generate augmentation samples
      run: |
        echo "Generating augmentation samples..."
        python -c "
        from augmentation import DataAugmentation
        augmentation = DataAugmentation()
        augmentation.visualize_augmentations(num_samples=10, save_path='outputs/augmentation_samples.png')
        "
        echo "Augmentation samples saved to outputs/augmentation_samples.png"


    - name: Train model
      run: |
        echo "Starting model training..."
        python train_model.py
        echo "Training completed."

    - name: Run model tests
      run: |
        echo "Running model tests..."
        python test_model.py
