name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ERA_V3/Assignment5
        pip install -r requirements.txt
    
    - name: Create models directory
      run: |
        cd ERA_V3/Assignment5
        mkdir -p models
    
    - name: Train model
      run: |
        cd ERA_V3/Assignment5
        python train_model.py
    
    - name: Test model
      run: |
        cd ERA_V3/Assignment5
        python test_model.py