name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: python train_model.py
      
    - name: Run tests
      run: python test_model.py
      
    - name: Archive model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        retention-days: 90