name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'pip'
    
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        echo "Current directory contents:"
        ls -R
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.1.0 torchvision==0.16.0 numpy==1.24.3 tqdm==4.66.1 pytest==7.4.3 gitpython==3.1.40 pillow==10.1.0 matplotlib==3.7.3
    
    - name: Create models directory
      run: |
        mkdir -p models
    
    - name: Train model
      run: |
        python train_model.py
    
    - name: Test model
      run: |
        python test_model.py