name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        cd ERA_V3/Assignment5
        python train_model.py
    
    - name: Test model
      run: |
        cd ERA_V3/Assignment5
        python test_model.py $(ls models/model_*.pth | tail -n 1) 